language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: I7ffcOkIXpKvTNoSYq2UZPPfF0Ky+WuDra4JGvez5unHX4mWmyGyFiEPE6scqzdlCp4Jp+jfFU8HHiRSunAtV/JTd42nLWhscSzaQINpWzQMOeIFMIfSR+Eywh3+vYKv8VjEmQKTWNRPjwcYfR85ykvoSIeh9UucrXcY2jmYPN8=
  file:
    - 'fault.js'
    - 'fault.min.js'
  on:
    tags: true
